### ISSUE TITLE
Unhandled error inside the library

### ISSUE THREAD

**Issue by esosphera-com** [modernmt/modernmt-node#2]
Hello, there is an instance of SyntaxError inside the library that is not caught/handled which leads to the crash of the node process. The error is not caught by a try-catch block around the translate method at library-user external level, because the error escapes the try catch block. 

More in details, this is the error:
``` 
SyntaxError: Unexpected token < in JSON at position 0
   at JSON.parse (<anonymous>)
   at IncomingMessage.<anonymous> (/es/srv/node/chat_server/agent_proxy/node_modules/modernmt/dist/utils/https.js:44:39)
   at IncomingMessage.emit (events.js:412:35)
   at IncomingMessage.emit (domain.js:470:12)
   at endReadableNT (internal/streams/readable.js:1317:12)
   at processTicksAndRejections (internal/process/task_queues.js:82:21) 
```
I believe the problem is in the file utils/https.ts at line 60 where it parses the JSON response. If the response does not contain a valid JSON (in my case I suppose it contains an HTML string) the JSON.parse function throws an exception that is not caught and handled with a promise rejection.
While the whole body of the promise is automatically wrapped in an implicit try-catch that causes the automatic rejection of the promise, I believe that in this case the exception escapes because it is thrown inside a callback executed on an event (the end of the api call's response)

Wrapping the JSON.parse in a try-catch block and rejecting the promise in case of exception should be enough to fix the problem.

Thanks,
Andrea

**Comment by davc0n** [comment]
Hi Andrea,

Thanks a lot for reporting this, the issue has been fixed in v1.0.12
