### ISSUE TITLE
Internal interface causes build error

### ISSUE THREAD

**Issue by AlexFalappa** [modernmt/modernmt-node#4]
When using `"modernmt": "^1.5.0"` dependency in my `package.json` and issuing a build command I get the following complaint by `ttsc`:
```
$ ttsc && cp .env* dist/
node_modules/modernmt/dist/modernmt.d.ts:1:60 - error TS2305: Module '"./types"' has no exported member 'HttpClient'.

1 import { BatchTranslation, DetectedLanguage, GlossaryTerm, HttpClient, ImportJob, Memory, QualityEstimation, TranslateOptions, Translation, User } from "./types";
                                                             ~~~~~~~~~~


Found 1 error in node_modules/modernmt/dist/modernmt.d.ts:1

error Command failed with exit code 2.
```

The `HttpClient` interface is indeed marked `@internal` in the library code.

Please consider removing the `@internal` marker or avoid stripping internal types.

**Comment by davc0n** [comment]
> The HttpClient interface is indeed marked @internal in the library code.

That's correct. Probably your issue is related to `ttsc`.
